name: Deploy Backend (FastAPI) to Azure Web App

on:
  push:
    branches:
      - user-testing

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches the Python version you need

    - name: Install dependencies
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip

        # Make the virtual environment inside the project root, wwwroot (backend folder)
        python -m venv /home/site/wwwroot/venv 

        # Activate the venv
        source /home/site/wwwroot/venv/bin/activate 

        # Install requirements inside the venv 
        pip install -r /home/site/wwwroot/requirements.txt 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: electionsystem-backend
        slot-name: production
        package: ./backend  # Deploy the contents of the backend folder
