name: Deploy Backend (FastAPI) to Azure Web App

on:
  push:
    branches:
      - user-testing

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches the Python version you need

    - name: Install dependencies
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip

        # Make the virtual environment inside the project root
        # Deployed package is ./backend, which has its contents copied inside of /home/site/wwwroot
        # /home/site/wwwroot is the current working directory of all instructions in the yaml. 
        python -m venv venv 

        # Activate the venv
        source venv/bin/activate 

        # Install requirements inside the venv 
        pip install -r requirements.txt 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: electionsystem-backend
        slot-name: production
        package: ./backend  # Deploy the contents of the backend folder
