name: Deploy Backend (FastAPI) to Azure Web App

on:
  push:
    branches:
      - user-testing

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches the Python version you need

    - name: Install dependencies
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip

        # Before deployment, the working directory is the project root.
        # After deployment, the working directory is /backend.
        # This backend folder has its contents copied to wwwroot, which becomes the new working directory.
        # This means files in the repo root, not in the backend folder, will be lost.
        # Hence we must create the venv inside of the backend folder. 
        python -m venv backend/venv 

        # Activate the venv
        source backend/venv/bin/activate 

        # Install requirements inside the venv 
        pip install -r backend/requirements.txt 

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: electionsystem-backend
        slot-name: production
        package: ./backend  # Deploy the contents of the backend folder
