name: Deploy Backend (FastAPI) to Azure Web App

on:
  push:
    branches:
      - user-testing

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches the Python version you need

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Make sure Oryx knows this is a python project and it needs building.
    - name: Build and Package App
      uses: azure/appservice-build@v1
      with:
        platform: python
        platform-version: '3.12'
        source-directory: ./backend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: electionsystem-backend
        slot-name: production
        # Deploy the contents of the backend folder. Azure auto creates a venv using requirements.txt
        # inside of the working directory, wwwroot, in a folder called antenv.
        package: ./backend  
        python_version: '3.12'
